type ControlCodeItem = {
  type: "CSI" | "DCS" | "DEC" | "OSC" | "ESC" | "SGR" | "STRING" | "PRIVATE";
  code: string;
  mnemonic?: string;
  description: string;
  template?: string;
  example?: { [key: string]: string };
  defaults?: { [key: string]: string };
  params?: { [key: string]: string };
  end?: { description: string; template: string };
};

export const controlCodes: ControlCodeItem[] = [
  { type: "SGR", code: "0", description: "reset" },
  { type: "SGR", code: "1", description: "bold" },
  { type: "SGR", code: "1:2", description: "shadow" },
  { type: "SGR", code: "2", description: "dim" },
  { type: "SGR", code: "3", description: "italic" },
  { type: "SGR", code: "4", description: "underline" },
  { type: "SGR", code: "4:0", description: "no underline" },
  { type: "SGR", code: "4:1", description: "single underline" },
  { type: "SGR", code: "4:2", description: "double underline" },
  { type: "SGR", code: "4:3", description: "curly underline" },
  { type: "SGR", code: "4:4", description: "dotted underline" },
  { type: "SGR", code: "4:5", description: "dashed underline" },
  { type: "SGR", code: "5", description: "slow blink" },
  { type: "SGR", code: "6", description: "rapid blink" },
  { type: "SGR", code: "7", description: "reverse video" },
  { type: "SGR", code: "8", description: "conceal" },
  { type: "SGR", code: "8:7", description: "overstrike" },
  { type: "SGR", code: "9", description: "strike-through" },
  { type: "SGR", code: "10", description: "default font" },
  { type: "SGR", code: "11", description: "alternate font 1" },
  { type: "SGR", code: "12", description: "alternate font 2" },
  { type: "SGR", code: "13", description: "alternate font 3" },
  { type: "SGR", code: "14", description: "alternate font 4" },
  { type: "SGR", code: "15", description: "alternate font 5" },
  { type: "SGR", code: "16", description: "alternate font 6" },
  { type: "SGR", code: "17", description: "alternate font 7" },
  { type: "SGR", code: "18", description: "alternate font 8" },
  { type: "SGR", code: "19", description: "alternate font 9" },
  { type: "SGR", code: "20", description: "alternate font 10" },
  { type: "SGR", code: "21", description: "double underline" },
  { type: "SGR", code: "22", description: "reset bold/dim" },
  { type: "SGR", code: "23", description: "reset italic/alternate font" },
  { type: "SGR", code: "24", description: "reset underline" },
  { type: "SGR", code: "25", description: "reset blink" },
  { type: "SGR", code: "27", description: "reset reversed video" },
  { type: "SGR", code: "28", description: "reset conceal/overstrike" },
  { type: "SGR", code: "29", description: "reset strike-through" },
  { type: "SGR", code: "30", description: "black foreground" },
  { type: "SGR", code: "31", description: "red foreground" },
  { type: "SGR", code: "32", description: "green foreground" },
  { type: "SGR", code: "33", description: "yellow foreground" },
  { type: "SGR", code: "34", description: "blue foreground" },
  { type: "SGR", code: "35", description: "magenta foreground" },
  { type: "SGR", code: "36", description: "cyan foreground" },
  { type: "SGR", code: "37", description: "white foreground" },
  { type: "SGR", code: "38;2", description: "set foreground color (24-bit true color)", template: ";<r>;<g>;<b>", example: { r: "255", g: "105", b: "180" } },
  { type: "SGR", code: "38;5", description: "set foreground color (256-color palette)", template: ";<n>", example: { n: "40" } },
  { type: "SGR", code: "39", description: "default foreground color" },
  { type: "SGR", code: "40", description: "black background" },
  { type: "SGR", code: "41", description: "red background" },
  { type: "SGR", code: "42", description: "green background" },
  { type: "SGR", code: "43", description: "yellow background" },
  { type: "SGR", code: "44", description: "blue background" },
  { type: "SGR", code: "45", description: "magenta background" },
  { type: "SGR", code: "46", description: "cyan background" },
  { type: "SGR", code: "47", description: "white background" },
  { type: "SGR", code: "48;2", description: "set background color (24-bit true color)", template: ";<r>;<g>;<b>", example: { r: "255", g: "105", b: "18" } },
  { type: "SGR", code: "48;5", description: "set background color (256-color palette)", template: ";<n>", example: { n: "198" } },
  { type: "SGR", code: "58;2", description: "set underline color (24-bit true color)", template: ";<r>;<g>;<b>", example: { r: "255", g: "105", b: "18" } },
  { type: "SGR", code: "58;5", description: "set underline color (256-color palette)", template: ";<n>", example: { n: "198" } },
  { type: "SGR", code: "49", description: "default background color" },
  { type: "SGR", code: "51", description: "frame" },
  { type: "SGR", code: "52", description: "encircle" },
  { type: "SGR", code: "53", description: "overline" },
  { type: "SGR", code: "54", description: "reset frame/encircle" },
  { type: "SGR", code: "55", description: "reset overline" },
  { type: "SGR", code: "59", description: "reset underline color" },
  { type: "SGR", code: "73", description: "superscript" },
  { type: "SGR", code: "74", description: "subscript" },
  { type: "SGR", code: "75", description: "reset super/subscript" },
  { type: "SGR", code: "90", description: "bright black foreground" },
  { type: "SGR", code: "91", description: "bright red foreground" },
  { type: "SGR", code: "92", description: "bright green foreground" },
  { type: "SGR", code: "93", description: "bright yellow foreground" },
  { type: "SGR", code: "94", description: "bright blue foreground" },
  { type: "SGR", code: "95", description: "bright magenta foreground" },
  { type: "SGR", code: "96", description: "bright cyan foreground" },
  { type: "SGR", code: "97", description: "bright white foreground" },
  { type: "SGR", code: "100", description: "bright black background" },
  { type: "SGR", code: "101", description: "bright red background" },
  { type: "SGR", code: "102", description: "bright green background" },
  { type: "SGR", code: "103", description: "bright yellow background" },
  { type: "SGR", code: "104", description: "bright blue background" },
  { type: "SGR", code: "105", description: "bright magenta background" },
  { type: "SGR", code: "106", description: "bright cyan background" },
  { type: "SGR", code: "107", description: "bright white background" },
  { type: "ESC", code: "6", mnemonic: "DECBI", description: "back index" },
  { type: "ESC", code: "7", mnemonic: "DECSC", description: "save cursor pos" },
  { type: "ESC", code: "8", mnemonic: "DECRC", description: "restore cursor pos" },
  { type: "ESC", code: "9", mnemonic: "DECFI", description: "forward index" },
  { type: "ESC", code: "=", mnemonic: "DECPAM", description: "application keypad" },
  { type: "ESC", code: ">", mnemonic: "DECPNM", description: "normal keypad" },
  { type: "ESC", code: "D", mnemonic: "IND", description: "index" },
  { type: "ESC", code: "E", mnemonic: "NEL", description: "next line" },
  { type: "ESC", code: "H", mnemonic: "HTS", description: "horizontal tab set" },
  { type: "ESC", code: "M", mnemonic: "RI", description: "reverse index" },
  { type: "ESC", code: "P", mnemonic: "DCS", description: "device control string" },
  { type: "ESC", code: "X", mnemonic: "PM", description: "privacy message" },
  { type: "ESC", code: "Z", mnemonic: "DECID", description: "identify device" },
  { type: "ESC", code: "c", mnemonic: "RIS", description: "reset to initial state" },
  { type: "ESC", code: "l", description: "memory lock" },
  { type: "ESC", code: "n", mnemonic: "LS2", description: "invoke G2 char set" },
  { type: "ESC", code: "o", mnemonic: "LS3", description: "invoke G3 char set" },
  { type: "ESC", code: "~", mnemonic: "LS1R", description: "invoke G1 char set as GR" },
  { type: "ESC", code: "}", mnemonic: "LS2R", description: "invoke G2 char set as GR" },
  { type: "ESC", code: "|", mnemonic: "LS3R", description: "invoke G3 char set as GR" },
  { type: "ESC", code: "<", description: "VT52 mode" },
  { type: "ESC", code: "_", mnemonic: "APC", description: "APC string" },
  { type: "ESC", code: "[", mnemonic: "CSI", description: "control sequence introducer" },
  { type: "ESC", code: "\\", mnemonic: "ST", description: "string terminator" },
  { type: "ESC", code: "]", mnemonic: "OSC", description: "operating system command" },
  { type: "ESC", code: "^", mnemonic: "SOS", description: "start of string" },
  { type: "ESC", code: " F", mnemonic: "S7C1T", description: "send 7-bit C1 controls" },
  { type: "ESC", code: " G", mnemonic: "S8C1T", description: "send 8-bit C1 controls" },
  { type: "ESC", code: " L", description: "set ANSI conformance level 1" },
  { type: "ESC", code: " M", description: "set ANSI conformance level 2" },
  { type: "ESC", code: " N", description: "set ANSI conformance level 3" },
  { type: "ESC", code: " O", description: "set ANSI conformance level 4" },
  { type: "ESC", code: "(A", mnemonic: "SCS", description: "G0: select UK char set" },
  { type: "ESC", code: "(B", mnemonic: "SCS", description: "G0: select ASCII char set" },
  { type: "ESC", code: "(0", mnemonic: "SCS", description: "G0: select special graphics set" },
  { type: "ESC", code: "(1", mnemonic: "SCS", description: "G0: select alternate ROM standard char set" },
  { type: "ESC", code: "(2", mnemonic: "SCS", description: "G0: select alternate ROM special graphics set" },
  { type: "ESC", code: ")A", mnemonic: "SCS", description: "G1: select UK char set" },
  { type: "ESC", code: ")B", mnemonic: "SCS", description: "G1: select ASCII char set" },
  { type: "ESC", code: ")0", mnemonic: "SCS", description: "G1: select special graphics set" },
  { type: "ESC", code: ")1", mnemonic: "SCS", description: "G1: select alternate ROM standard char set" },
  { type: "ESC", code: ")2", mnemonic: "SCS", description: "G1: select alternate ROM special graphics set" },
  { type: "ESC", code: "*A", mnemonic: "SCS", description: "G2: select UK char set" },
  { type: "ESC", code: "*B", mnemonic: "SCS", description: "G2: select ASCII char set" },
  { type: "ESC", code: "*0", mnemonic: "SCS", description: "G2: select special graphics set" },
  { type: "ESC", code: "*1", mnemonic: "SCS", description: "G2: select alternate ROM standard char set" },
  { type: "ESC", code: "*2", mnemonic: "SCS", description: "G2: select alternate ROM special graphics set" },
  { type: "ESC", code: "+A", mnemonic: "SCS", description: "G3: select UK char set" },
  { type: "ESC", code: "+B", mnemonic: "SCS", description: "G3: select ASCII char set" },
  { type: "ESC", code: "+0", mnemonic: "SCS", description: "G3: select special graphics set" },
  { type: "ESC", code: "+1", mnemonic: "SCS", description: "G3: select alternate ROM standard char set" },
  { type: "ESC", code: "+2", mnemonic: "SCS", description: "G3: select alternate ROM special graphics set" },
  { type: "ESC", code: "%@", description: "select default char set" },
  { type: "ESC", code: "%G", description: "select UTF-8 char set" },
  { type: "ESC", code: "#3", mnemonic: "DECDHL", description: "double-height line, top half" },
  { type: "ESC", code: "#4", mnemonic: "DECDHL", description: "double-height line, bottom half" },
  { type: "ESC", code: "#5", mnemonic: "DECSWL", description: "single-width, single-height characters" },
  { type: "ESC", code: "#6", mnemonic: "DECDWL", description: "double-width, single-height characters" },
  { type: "ESC", code: "#8", mnemonic: "DECALN", description: "screen alignment pattern" },
  { type: "ESC", code: "D", mnemonic: "IND", description: "index" },
  { type: "ESC", code: "E", mnemonic: "NEL", description: "next line" },
  { type: "ESC", code: "H", mnemonic: "HTS", description: "horizontal tab set" },
  { type: "ESC", code: "K", mnemonic: "VTS", description: "vertical tab set" },
  { type: "ESC", code: "M", mnemonic: "RI", description: "reverse index" },
  { type: "ESC", code: "N", mnemonic: "SS2", description: "single shift 2" },
  { type: "ESC", code: "O", mnemonic: "SS3", description: "single shift 3" },
  { type: "ESC", code: "Z", mnemonic: "DECID", description: "identify device" },
  { type: "ESC", code: "c", mnemonic: "RIS", description: "reset to initial state" },
  { type: "ESC", code: "7", mnemonic: "DECSC", description: "save cursor pos" },
  { type: "ESC", code: "8", mnemonic: "DECRC", description: "restore cursor pos" },
  { type: "CSI", code: "@", mnemonic: "ICH", description: "insert characters", template: "<n> chars", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "A", mnemonic: "CUU", description: "move cursor up", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "B", mnemonic: "CUD", description: "move cursor down", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "C", mnemonic: "CUF", description: "move cursor forward", template: "<cols> cols", example: { cols: "1" }, defaults: { cols: "1" } },
  { type: "CSI", code: "D", mnemonic: "CUB", description: "move cursor back", template: "<cols> cols", example: { cols: "1" }, defaults: { cols: "1" } },
  { type: "CSI", code: "E", mnemonic: "CNL", description: "move cursor to next line", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "F", mnemonic: "CPL", description: "move cursor to previous line", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "G", mnemonic: "CHA", description: "move cursor char absolute", template: "col <col>", example: { col: "1" }, defaults: { col: "1" } },
  { type: "CSI", code: "H", mnemonic: "CUP", description: "move cursor pos", template: "row <row>, col <col>", example: { row: "1", col: "1" }, defaults: { row: "1", col: "1" } },
  { type: "CSI", code: "I", mnemonic: "CHT", description: "move cursor horizontal tabulation", template: "<n> tabs", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "J", mnemonic: "ED", description: "erase", params: { "0": "from cursor to end of screen", "1": "from cursor to beginning of screen", "2": "entire screen", "3": "entire screen and clear scrollback buffer" }, defaults: { mode: "0" } },
  { type: "CSI", code: "K", mnemonic: "EL", description: "erase", params: { "0": "from cursor to end of line", "1": "from cursor to beginning of line", "2": "entire line" }, defaults: { mode: "0" } },
  { type: "CSI", code: "L", mnemonic: "IL", description: "insert lines", template: "<n> lines", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "M", mnemonic: "DL", description: "delete lines", template: "<n> lines", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "N", mnemonic: "EF", description: "erase in field", params: { "0": "from cursor to end of field", "1": "from beginning of field to cursor", "2": "entire field" }, defaults: { mode: "0" } },
  { type: "CSI", code: "O", mnemonic: "EA", description: "erase in area", params: { "0": "from cursor to end of area", "1": "from beginning of area to cursor", "2": "entire area" }, defaults: { mode: "0" } },
  { type: "CSI", code: "P", mnemonic: "DCH", description: "delete characters", template: "<n> chars", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "Q", mnemonic: "SEE", description: "select editing extent", params: { "0": "entire buffer", "1": "active line", "2": "between horizontal tabs", "3": "qualified area" }, defaults: { mode: "0" } },
  { type: "CSI", code: "R", mnemonic: "CPR", description: "cursor pos report", template: "row <row>, col <col>", example: { row: "1", col: "1" }, defaults: { row: "1", col: "1" } },
  { type: "CSI", code: "S", mnemonic: "SU", description: "scroll up (pan down)", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "T", mnemonic: "SD", description: "scroll down (pan up)", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "U", mnemonic: "NP", description: "next page", template: "<n> pages", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "V", mnemonic: "PP", description: "preceding page", template: "<n> pages", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "W", mnemonic: "CTC", description: "cursor tab control", params: { "0": "set horizontal tab at active pos", "1": "set vertical tab at active line", "2": "clear horizontal tab at active pos", "3": "clear vertical tab at active line", "4": "clear all horizontal tabs at active line", "5": "clear all horizontal tabs", "6": "clear all vertical tabs" }, defaults: { mode: "0" } },
  { type: "CSI", code: "X", mnemonic: "ECH", description: "erase characters", template: "<n> chars", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "Y", mnemonic: "CVT", description: "cursor vertical tabulation", template: "<n> tabs", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "Z", mnemonic: "CBT", description: "cursor backward tabulation", template: "<n> tabs", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "`", mnemonic: "HPA", description: "horizontal cursor pos absolute", template: "col <col>", example: { col: "1" }, defaults: { col: "1" } },
  { type: "CSI", code: "a", mnemonic: "HPR", description: "horizontal cursor pos relative", template: "<cols> cols", example: { cols: "1" }, defaults: { cols: "1" } },
  { type: "CSI", code: "b", mnemonic: "REP", description: "repeat character", template: "<n> times", example: { n: "1" }, defaults: { n: "1" } },
  { type: "CSI", code: "c", mnemonic: "DA", description: "device attributes", params: { "0": "request primary device attrs", ">0": "request secondary device attrs" }, defaults: { mode: "0" } },
  { type: "CSI", code: "d", mnemonic: "VPA", description: "vertical cursor pos absolute", template: "row <row>", example: { row: "1" }, defaults: { row: "1" } },
  { type: "CSI", code: "e", mnemonic: "VPR", description: "vertical cursor pos relative", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "f", mnemonic: "HVP", description: "horizontal vertical cursor pos", template: "row <row>, col <col>", example: { row: "1", col: "1" }, defaults: { row: "1", col: "1" } },
  { type: "CSI", code: "g", mnemonic: "TBC", description: "tab clear", params: { "0": "clear current column", "3": "clear all tabs" }, defaults: { mode: "0" } },
  { type: "CSI", code: "h", mnemonic: "SM", description: "set mode", params: { "4": "insert mode (IRM)", "20": "automatic newline (LNM)" }, defaults: { mode: "" } },
  { type: "CSI", code: "i", mnemonic: "MC", description: "media copy", params: { "0": "print screen", "4": "printer mode off", "5": "printer mode on" }, defaults: { mode: "0" } },
  { type: "CSI", code: "j", mnemonic: "HPB", description: "horizontal pos backward", template: "<cols> cols", example: { cols: "1" }, defaults: { cols: "1" } },
  { type: "CSI", code: "k", mnemonic: "VPB", description: "vertical pos backward", template: "<rows> rows", example: { rows: "1" }, defaults: { rows: "1" } },
  { type: "CSI", code: "l", mnemonic: "RM", description: "reset mode", params: { "4": "replace mode (IRM)", "20": "normal linefeed (LNM)" }, defaults: { mode: "" } },
  { type: "CSI", code: "m", mnemonic: "SGR", description: "select graphic rendition", defaults: { attribute: "0" } },
  { type: "CSI", code: "n", mnemonic: "DSR", description: "device status report", params: { "5": "status report", "6": "report cursor pos", R: "report cursor pos response", "0": "ready" }, defaults: { mode: "0" } },
  { type: "CSI", code: "q", mnemonic: "DECLL", description: "load LEDs", params: { "0": "turn off all LEDs", "1": "turn on LED 1", "2": "turn on LED 2", "3": "turn on LED 3", "4": "turn on LED 4" }, defaults: { led: "0" } },
  { type: "CSI", code: "r", mnemonic: "DECSTBM", description: "set scrolling region", template: "top <top>, bottom <bottom>", example: { top: "1", bottom: "24" }, defaults: { top: "1", bottom: "screen height" } },
  { type: "CSI", code: "s", mnemonic: "SCP", description: "save cursor pos" },
  { type: "CSI", code: "t", description: "window manipulation" },
  { type: "CSI", code: "u", mnemonic: "RCP", description: "restore cursor pos" },
  { type: "CSI", code: "x", mnemonic: "DECREQTPARM", description: "request terminal parameters" },
  { type: "CSI", code: "y", mnemonic: "DECTSDT", description: "test diagnostic data" },
  { type: "CSI", code: "o", mnemonic: "DAQ", description: "define area qualification", params: { "0": "unprotected", "1": "guarded (protected)", "2": "graphic char input", "3": "numeric input", "4": "alphabetic input", "5": "input justified right", "6": "fill with zeros", "7": "set horizontal tab", "8": "protected (unguarded)", "9": "fill with spaces" }, defaults: { mode: "0" } },
  { type: "CSI", code: " q", mnemonic: "DECSCUSR", description: "set cursor style", template: "style <style>", example: { style: "2" }, defaults: { style: "1" } },
  { type: "CSI", code: " t", mnemonic: "DECSWBV", description: "set warning bell volume" },
  { type: "CSI", code: " u", mnemonic: "DECSMBV", description: "set margin bell volume" },
  { type: "CSI", code: " @", mnemonic: "SL", description: "scroll left", template: "<cols> cols", example: { cols: "1" }, defaults: { cols: "1" } },
  { type: "CSI", code: " A", mnemonic: "SR", description: "scroll right", template: "<cols> cols", example: { cols: "1" }, defaults: { cols: "1" } },
  { type: "CSI", code: " B", mnemonic: "GSM", description: "graphic size modification", template: "height <height>%, width <width>%", example: { height: "100", width: "100" }, defaults: { height: "100", width: "100" } },
  { type: "CSI", code: " D", mnemonic: "FNT", description: "font selection", template: "font <font>, id <id>", example: { font: "0", id: "0" }, defaults: { font: "0", id: "0" } },
  { type: "CSI", code: " F", mnemonic: "JFY", description: "justify", params: { "0": "end justification", "1": "word fill", "2": "interword space", "3": "letter space", "4": "hyphenation", "5": "flush left", "6": "center", "7": "flush right", "8": "Italian hyphenation" }, defaults: { mode: "0" } },
  { type: "CSI", code: " H", mnemonic: "QUAD", description: "quad", params: { "0": "flush left", "1": "flush left with leader", "2": "center", "3": "center with leader", "4": "flush right", "5": "flush right with leader" }, defaults: { mode: "0" } },
  { type: "CSI", code: " I", mnemonic: "SSU", description: "select size unit", params: { "1": "international typographic standard", "2": "decipoint (1/720 inch)", "3": "didot", "4": "mil (1/1000 inch)", "5": "metric (0.01 mm)" }, defaults: { unit: "" } },
  { type: "CSI", code: " J", mnemonic: "GSS", description: "graphic size selection", template: "height <height>", example: { height: "12" }, defaults: { height: "" } },
  { type: "CSI", code: " K", mnemonic: "SPI", description: "spacing increment", template: "interline <interline>, space <space>", example: { interline: "12", space: "6" }, defaults: { interline: "", space: "" } },
  { type: "CSI", code: " L", mnemonic: "TSS", description: "thin space specification", template: "width <width>", example: { width: "3" }, defaults: { width: "" } },
  { type: "CSI", code: "!p", mnemonic: "DECSTR", description: "soft terminal reset" },
  { type: "CSI", code: '"p', mnemonic: "DECSCL", description: "select conformance level", template: "level <level>, mode <mode>", example: { level: "64", mode: "1" } },
  { type: "CSI", code: '"q', mnemonic: "DECSCA", description: "select char protection attribute", template: "<attr>", example: { attr: "1" } },
  { type: "CSI", code: "$p", mnemonic: "DECRQM", description: "request ANSI mode" },
  { type: "CSI", code: "$r", mnemonic: "DECCARA", description: "change attributes in rectangular area" },
  { type: "CSI", code: "$t", mnemonic: "DECRARA", description: "reverse attributes in rectangular area" },
  { type: "CSI", code: "$v", mnemonic: "DECCRA", description: "copy rectangular area" },
  { type: "CSI", code: "$x", mnemonic: "DECFRA", description: "fill rectangular area" },
  { type: "CSI", code: "$z", mnemonic: "DECERA", description: "erase rectangular area" },
  { type: "DEC", code: "1", mnemonic: "DECCKM", description: "cursor key to application" },
  { type: "DEC", code: "2", mnemonic: "DECANM", description: "ANSI mode" },
  { type: "DEC", code: "3", mnemonic: "DECCOLM", description: "number of columns to 132" },
  { type: "DEC", code: "4", mnemonic: "DECSCLM", description: "smooth scrolling" },
  { type: "DEC", code: "5", mnemonic: "DECSCNM", description: "screen mode to reverse video" },
  { type: "DEC", code: "6", mnemonic: "DECOM", description: "origin mode to relative" },
  { type: "DEC", code: "7", mnemonic: "DECAWM", description: "auto-wrap mode" },
  { type: "DEC", code: "8", mnemonic: "DECARM", description: "auto-repeat keys" },
  { type: "DEC", code: "9", mnemonic: "DECINLM", description: "interlace mode" },
  { type: "DEC", code: "10", description: "show toolbar" },
  { type: "DEC", code: "12", description: "blinking cursor" },
  { type: "DEC", code: "18", mnemonic: "DECPFF", description: "print feed form" },
  { type: "DEC", code: "19", mnemonic: "DECPEX", description: "print extent" },
  { type: "DEC", code: "25", mnemonic: "DECTCEM", description: "show cursor" },
  { type: "DEC", code: "30", description: "show scrollbar" },
  { type: "DEC", code: "35", description: "enable font-shifting" },
  { type: "DEC", code: "38", mnemonic: "DECTEK", description: "enter Tektronix mode" },
  { type: "DEC", code: "40", description: "allow 80->132 column mode" },
  { type: "DEC", code: "41", description: "more(1) fix" },
  { type: "DEC", code: "42", mnemonic: "DECNRCM", description: "national/multinational char mode" },
  { type: "DEC", code: "44", description: "margin bell" },
  { type: "DEC", code: "45", description: "reverse-wraparound mode" },
  { type: "DEC", code: "46", description: "start logging" },
  { type: "DEC", code: "47", description: "alternate screen buffer" },
  { type: "DEC", code: "66", mnemonic: "DECNKM", description: "application keypad mode" },
  { type: "DEC", code: "67", description: "backarrow sends backspace" },
  { type: "DEC", code: "69", mnemonic: "DECVSSM", description: "vertical split screen mode" },
  { type: "DEC", code: "95", description: "don't clear screen on DECCOLM" },
  { type: "DEC", code: "1000", description: "VT200 mouse reporting" },
  { type: "DEC", code: "1001", description: "X11 mouse reporting" },
  { type: "DEC", code: "1002", description: "button-event mouse reporting" },
  { type: "DEC", code: "1003", description: "any-event mouse reporting" },
  { type: "DEC", code: "1004", description: "focus in/out events" },
  { type: "DEC", code: "1005", description: "UTF-8 mouse mode" },
  { type: "DEC", code: "1006", description: "SGR mouse mode" },
  { type: "DEC", code: "1007", description: "alternate scroll mode" },
  { type: "DEC", code: "1010", description: "scroll to bottom on tty output" },
  { type: "DEC", code: "1011", description: "scroll to bottom on keypress" },
  { type: "DEC", code: "1015", description: "urxvt mouse mode" },
  { type: "DEC", code: "1016", description: "SGR mouse pixel mode" },
  { type: "DEC", code: "1034", description: "8-bit meta key" },
  { type: "DEC", code: "1035", description: "numeric keypad meta key" },
  { type: "DEC", code: "1036", description: "alternate key modifiers" },
  { type: "DEC", code: "1037", description: "delete key to send DEL" },
  { type: "DEC", code: "1039", description: "alternate backspace" },
  { type: "DEC", code: "1040", description: "keep selection even if not highlighted" },
  { type: "DEC", code: "1041", description: "use CLIPBOARD selection" },
  { type: "DEC", code: "1042", description: "bell to urgent" },
  { type: "DEC", code: "1043", description: "enable raising window on BEL" },
  { type: "DEC", code: "1044", description: "reuse most recent data to CLIPBOARD" },
  { type: "DEC", code: "1047", description: "alternate screen mode" },
  { type: "DEC", code: "1048", description: "extended cursor mode" },
  { type: "DEC", code: "1049", description: "alternate screen buffer (cursor save/restore)" },
  { type: "DEC", code: "1050", description: "termcap/terminfo special keys" },
  { type: "DEC", code: "1051", description: "Sun function keys" },
  { type: "DEC", code: "1052", description: "HP function keys" },
  { type: "DEC", code: "1053", description: "SCO function keys" },
  { type: "DEC", code: "1060", description: "legacy xterm keys" },
  { type: "DEC", code: "1061", description: "VT220 keyboard" },
  { type: "DEC", code: "2004", description: "bracketed paste mode" },
  { type: "DEC", code: "1062", description: "VT220 function keys" },
  { type: "DEC", code: "1070", description: "six-key function keys" },
  { type: "DEC", code: "2026", description: "synchronized output mode" },
  { type: "DEC", code: "1014", description: "use CLIPBOARD for special paste" },
  { type: "DEC", code: "1016", description: "SGR mouse pixel mode" },
  { type: "DEC", code: "1021", description: "bold key sends DEL" },
  { type: "DEC", code: "1022", description: "Sun function key mode" },
  { type: "DEC", code: "1023", description: "meta sends ESC" },
  { type: "DEC", code: "1038", description: "Alt key mode" },
  { type: "DEC", code: "1039", description: "Alt sends ESC prefix" },
  { type: "DEC", code: "1045", description: "extended reverse-wraparound mode" },
  { type: "DEC", code: "1046", description: "application cursor keys mode" },
  { type: "DEC", code: "1055", description: "VT200 highlighting" },
  { type: "DEC", code: "1056", description: "VT220 highlighting" },
  { type: "DEC", code: "1057", description: "VT320 highlighting" },
  { type: "OSC", code: "0", mnemonic: "OSC 0", description: "set window title and icon name", template: ";<text>", example: { text: "title" } },
  { type: "OSC", code: "1", mnemonic: "OSC 1", description: "set icon name", template: ";<text>", example: { text: "icon" } },
  { type: "OSC", code: "2", mnemonic: "OSC 2", description: "set window title", template: ";<text>", example: { text: "title" } },
  { type: "OSC", code: "3", mnemonic: "OSC 3", description: "set X property on top-level window" },
  { type: "OSC", code: "4", mnemonic: "OSC 4", description: "set/read palette color", template: ";<n>;<color-spec>", example: { n: "11", "color-spec": "rgb:00/ff/00" } },
  { type: "OSC", code: "5", mnemonic: "OSC 5", description: "change special color spec" },
  { type: "OSC", code: "6", mnemonic: "OSC 6", description: "enable special color" },
  { type: "OSC", code: "7", mnemonic: "OSC 7", description: "set current working directory", template: ";<url>", example: { url: "file://hostname/path" } },
  { type: "OSC", code: "8", mnemonic: "OSC 8", description: "hyperlink", template: ";<params>;<url>", example: { params: "id=1", url: "https://example.com" }, end: { description: "hyperlink (end)", template: "" } },
  { type: "OSC", code: "9", mnemonic: "OSC 9", description: "send notification", template: ";<message>", example: { message: "hello there" } },
  { type: "OSC", code: "10", mnemonic: "OSC 10", description: "set/read text foreground color", template: ";<color-spec>", example: { "color-spec": "rgb:ff/00/00" } },
  { type: "OSC", code: "11", mnemonic: "OSC 11", description: "set/read text background color", template: ";<color-spec>", example: { "color-spec": "rgb:00/00/ff" } },
  { type: "OSC", code: "12", mnemonic: "OSC 12", description: "set/read text cursor color", template: ";<color-spec>", example: { "color-spec": "rgb:00/ff/00" } },
  { type: "OSC", code: "13", mnemonic: "OSC 13", description: "change mouse foreground color" },
  { type: "OSC", code: "14", mnemonic: "OSC 14", description: "change mouse background color" },
  { type: "OSC", code: "15", mnemonic: "OSC 15", description: "change Tektronix foreground color" },
  { type: "OSC", code: "16", mnemonic: "OSC 16", description: "change Tektronix background color" },
  { type: "OSC", code: "17", mnemonic: "OSC 17", description: "change highlight color" },
  { type: "OSC", code: "18", mnemonic: "OSC 18", description: "change Tektronix cursor color" },
  { type: "OSC", code: "19", mnemonic: "OSC 19", description: "change highlight foreground color" },
  { type: "OSC", code: "46", mnemonic: "OSC 46", description: "set log file" },
  { type: "OSC", code: "50", mnemonic: "OSC 50", description: "set font" },
  { type: "OSC", code: "51", mnemonic: "OSC 51", description: "reserved for emacs shell" },
  { type: "OSC", code: "52", mnemonic: "OSC 52", description: "manipulate clipboard", template: ";<c>;<data>", example: { c: "c", data: "YmFzZTY0" } },
  { type: "OSC", code: "104", mnemonic: "OSC 104", description: "reset palette color", template: ";<n>", example: { n: "11" } },
  { type: "OSC", code: "105", mnemonic: "OSC 105", description: "reset special color spec" },
  { type: "OSC", code: "106", mnemonic: "OSC 106", description: "disable special color" },
  { type: "OSC", code: "110", mnemonic: "OSC 110", description: "reset dynamic color" },
  { type: "OSC", code: "111", mnemonic: "OSC 111", description: "reset dynamic color" },
  { type: "OSC", code: "112", mnemonic: "OSC 112", description: "reset dynamic color" },
  { type: "OSC", code: "113", mnemonic: "OSC 113", description: "reset dynamic color" },
  { type: "OSC", code: "114", mnemonic: "OSC 114", description: "reset dynamic color" },
  { type: "OSC", code: "115", mnemonic: "OSC 115", description: "reset dynamic color" },
  { type: "OSC", code: "116", mnemonic: "OSC 116", description: "reset dynamic color" },
  { type: "OSC", code: "117", mnemonic: "OSC 117", description: "reset dynamic color" },
  { type: "OSC", code: "118", mnemonic: "OSC 118", description: "reset dynamic color" },
  { type: "OSC", code: "119", mnemonic: "OSC 119", description: "reset dynamic color" },
  { type: "OSC", code: "133", mnemonic: "OSC 133", description: "FinalTerm shell integration" },
  { type: "OSC", code: "777", mnemonic: "OSC 777", description: "send notification (rxvt-unicode)", template: ";notify;<title>;<body>", example: { title: "subject", body: "hello" } },
  { type: "OSC", code: "1000", mnemonic: "OSC 1000", description: "xterm modification", template: ";<name>=<value>", example: { name: "resource", value: "setting" } },
  { type: "OSC", code: "1337", mnemonic: "OSC 1337", description: "iTerm2 shell integration" },
  { type: "DCS", code: "{", mnemonic: "DECDLD", description: "downloadable char set definition", template: ";<charset-data>", example: { "charset-data": "0;1;2;3;4;5;6;7" } },
  { type: "DCS", code: "|", mnemonic: "DECUDK", description: "user-defined keys", template: ";<key-definitions>", example: { "key-definitions": "5/4,7/~~" } },
  { type: "DCS", code: "$q", mnemonic: "DECRQSS", description: "request selection or setting", template: ";<setting>", example: { setting: "m" } },
  { type: "DCS", code: "+p", description: "set termcap/terminfo data", template: ";<termcap-data>", example: { "termcap-data": "xterm:co#80:li#24" } },
  { type: "DCS", code: "+q", description: "request termcap/terminfo string", template: ";<capability>", example: { capability: "Co" } },
  { type: "DCS", code: "$p", description: "DECRQSS request", template: ";<parameter>", example: { parameter: '"q' } },
  { type: "DCS", code: "$t", description: "restore presentation state", template: ";<state-data>", example: { "state-data": "presentation" } },
  { type: "DCS", code: "$u", description: "restore format state", template: ";<format-data>", example: { "format-data": "format" } },
  { type: "STRING", code: "APC", mnemonic: "APC", description: "application program command", template: ";<command>", example: { command: "custom application data" } },
  { type: "STRING", code: "PM", mnemonic: "PM", description: "privacy message", template: ";<message>", example: { message: "private data content" } },
  { type: "STRING", code: "SOS", mnemonic: "SOS", description: "start of string", template: ";<data>", example: { data: "string sequence data" } },
  { type: "PRIVATE", code: "<", description: "private sequence", template: ";<params>;<final>", example: { params: "1", final: "h" } },
  { type: "PRIVATE", code: "=", description: "private sequence", template: ";<params>;<final>", example: { params: "1", final: "c" } },
  { type: "PRIVATE", code: ">", description: "private sequence", template: ";<params>;<final>", example: { params: "0", final: "c" } },
];

export const codeMaps = {
  CSI: new Map<string, ControlCodeItem>(),
  DCS: new Map<string, ControlCodeItem>(),
  DEC: new Map<string, ControlCodeItem>(),
  ESC: new Map<string, ControlCodeItem>(),
  OSC: new Map<string, ControlCodeItem>(),
  PRIVATE: new Map<string, ControlCodeItem>(),
  SGR: new Map<string, ControlCodeItem>(),
  STRING: new Map<string, ControlCodeItem>(),
} as const;

for (const code of controlCodes) codeMaps[code.type].set(code.code, code);
