export const sgrParameters: { [key: string]: { description: string } } = {
  "0": { description: "reset" },
  "1": { description: "bold" },
  "2": { description: "dim" },
  "3": { description: "italic" },
  "4": { description: "underline" },
  "5": { description: "slow blink" },
  "6": { description: "rapid blink" },
  "7": { description: "reverse video" },
  "8": { description: "conceal" },
  "9": { description: "strike-through" },
  "21": { description: "double underline" },
  "22": { description: "normal (not bold)" },
  "23": { description: "not italic" },
  "24": { description: "not underlined" },
  "25": { description: "not blinking" },
  "27": { description: "not reversed" },
  "28": { description: "reveal" },
  "29": { description: "not strike-through" },
  "30": { description: "black foreground" },
  "31": { description: "red foreground" },
  "32": { description: "green foreground" },
  "33": { description: "yellow foreground" },
  "34": { description: "blue foreground" },
  "35": { description: "magenta foreground" },
  "36": { description: "cyan foreground" },
  "37": { description: "white foreground" },
  "38": { description: "foreground color (extended)" },
  "39": { description: "default foreground color" },
  "40": { description: "black background" },
  "41": { description: "red background" },
  "42": { description: "green background" },
  "43": { description: "yellow background" },
  "44": { description: "blue background" },
  "45": { description: "magenta background" },
  "46": { description: "cyan background" },
  "47": { description: "white background" },
  "48": { description: "background color (extended)" },
  "49": { description: "default background color" },
  "52": { description: "framed" },
  "53": { description: "overline" },
  "90": { description: "bright black foreground" },
  "91": { description: "bright red foreground" },
  "92": { description: "bright green foreground" },
  "93": { description: "bright yellow foreground" },
  "94": { description: "bright blue foreground" },
  "95": { description: "bright magenta foreground" },
  "96": { description: "bright cyan foreground" },
  "97": { description: "bright white foreground" },
  "100": { description: "bright black background" },
  "101": { description: "bright red background" },
  "102": { description: "bright green background" },
  "103": { description: "bright yellow background" },
  "104": { description: "bright blue background" },
  "105": { description: "bright magenta background" },
  "106": { description: "bright cyan background" },
  "107": { description: "bright white background" },
};

export const controlCodes: {
  [key: string]: {
    mnemonic?: string;
    description: string;
    params?: { [key: string]: string };
  };
} = {
  A: { mnemonic: "CUU", description: "cursor up" },
  B: { mnemonic: "CUD", description: "cursor down" },
  C: { mnemonic: "CUF", description: "cursor forward" },
  D: { mnemonic: "CUB", description: "cursor back" },
  E: { mnemonic: "CNL", description: "cursor next line" },
  F: { mnemonic: "CPL", description: "cursor previous line" },
  G: { mnemonic: "CHA", description: "cursor character absolute" },
  H: { mnemonic: "CUP", description: "cursor position" },
  J: {
    mnemonic: "ED",
    description: "erase in display",
    params: {
      "0": "erase from cursor to end of screen",
      "1": "erase from cursor to beginning of screen",
      "2": "erase entire screen",
      "3": "erase entire screen and clear scrollback buffer",
    },
  },
  K: {
    mnemonic: "EL",
    description: "erase in line",
    params: {
      "0": "erase from cursor to end of line",
      "1": "erase from cursor to beginning of line",
      "2": "erase entire line",
    },
  },
  S: { mnemonic: "SU", description: "scroll up" },
  T: { mnemonic: "SD", description: "scroll down" },
  c: { mnemonic: "RIS", description: "reset to initial state" },
  f: { mnemonic: "HVP", description: "horizontal vertical position" },
  h: { mnemonic: "SM", description: "mode" },
  l: { mnemonic: "RM", description: "remode" },
  m: { mnemonic: "SGR", description: "select graphic rendition" },
  n: { mnemonic: "DSR", description: "device status report" },
  s: { mnemonic: "SCP", description: "save cursor position" },
  u: { mnemonic: "RCP", description: "restore cursor position" },
};

export const privateModes: { [key: string]: { description: string; mnemonic?: string } } = {
  "1": { mnemonic: "DECCKM", description: "cursor keys (application mode)" },
  "3": { mnemonic: "DECCOLM", description: "132 column mode" },
  "5": { mnemonic: "DECSCNM", description: "reverse video mode" },
  "6": { mnemonic: "DECOM", description: "origin mode" },
  "7": { mnemonic: "DECAWM", description: "auto-wrap mode" },
  "8": { mnemonic: "DECARM", description: "auto-wrap mode" },
  "9": { description: "X10 mouse reporting" },
  "12": { description: "start blinking cursor" },
  "25": { mnemonic: "DECTECM", description: "show text cursor" },
  "47": { description: "use alternate screen buffer" },
  "1000": { description: "VT200 mouse reporting" },
  "1002": { description: "button-event mouse reporting" },
  "1003": { description: "any-event mouse reporting" },
  "1004": { description: "send focus in/out events" },
  "1049": { description: "alternate screen buffer with cursor save/restore" },
  "2004": { description: "bracketed paste mode" },
};
